version: '3.8'

services:
  # spin up a database
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD:
      POSTGRES_DB: capstone
    ports:
      - "5432"
    volumes:
      - capstone-db:/var/lib/postgresql/data

  # start up an API server
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    environment:
      DB_HOST: localhost
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      PORT: 3000
    ports:
      - "3000"
    depends_on:
      - postgres

  # start up a client (and proxy) server
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_ORIGIN: http://localhost:3001
        VITE_API_PATH: /api/v1/trpc
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  capstone-db:
